### ISSUE TITLE
Keyboard shortcut doesn't work in Picasa,Pathfinder or any app except Finder 

### ISSUE THREAD

**Issue by jitrulz** [deanishe/alfred-similar-image-search#1]
Hi,
First of all i want to thankyou for such a fabulous workflow. I was looking for this from years. 
I Just faced one problem, that it doesn't invoke search (by keyboard shortcut cmd+shift+F) from any other app except Finder. { by the way, I have added picasa,path finder apps in the "Related Apps" section and value selected in the dropdown is "on focus")
I usually keep lot of images in Picasa and it will be great to invoke similar image search right from with in it rather than going to finder , searching the same file and then pressing the keyboard shortcut.

Would appreciate any help. Thanks :)

**Comment by deanishe** [comment]
Yeah, the reason only Finder is in "Related Apps" is because the workflow only works with Finder (and Alfred's File Actions).

Adding other applications to "Related Apps" only tells Alfred to register the keyboard shortcut when those apps have focus; it doesn't make the workflow work with them.

The way the workflow works is it asks Finder via its scripting interface for the currently selected file(s) and then uploads the first one to Google.

It could be made to work with other apps, like Path Finder, that also have scripting interfaces (by writing an appropriate script for each one), but Picasa isn't scriptable, so there's no way (that I'm aware of) for the workflow to ask it which image is currently selected.
